- name: Service1
  price: 99.99
  description: description of Service1

- name: Service2
  price: 199.99
  description: description of Service2

- name: service3
  price: 299.99
  description: description of service3